name: run-tests-workflow

on: 
  workflow_dispatch
  
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - run: playwright install 
    - run: pytest tests
      env:
         HEADLESS: 'true'
  
