name: run-tests-workflow

on: 
  workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  run-tests-job:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install

    - name: Set up Allure
      run: |
        sudo apt-get install default-jre
        wget https://github.com/allure-framework/allure2/releases/download/2.18.1/allure_2.18.1-1_all.deb
        sudo dpkg -i allure_2.18.1-1_all.deb

    - name: Run tests
      run: pytest tests --alluredir=allure-results
      env:
         HEADLESS: 'true'

    - name: Combine report
      run: |
         allure generate allure-results --clean -o allure-report  
         allure-combine ./allure-report --dest ./tmp/result --auto-create-folders
    
    - uses: actions/upload-artifact@v3
    - name: Save the report
      with:
         name: tests-report
         path: output/tmp/result/complete.html
         retention-days: 30


    - name: Configure github pages
      uses: actions/upload-pages-artifact@v3
      with:
          path: 'output/tmp/result/complete.html'
          
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
  
